### ISSUE TITLE
Don't print color codes on non-color capable terminals

### ISSUE THREAD

**Issue by gvenzl** [gvenzl/csv2db#29]
Right now `csv2db` prints color codes regardless of whether the terminal is color capable or not:

```
C:\Users\gvenzl\Downloads\csv2db-1.4.0>csv2db lo -f test -t bla -u u -p p -v --debug
[33mDEBUG: 2019-11-10 18:18:39.460232: Table name: bla
[0m[33mDEBUG: 2019-11-10 18:18:39.460232: Column separator: ,
[0m[33mDEBUG: 2019-11-10 18:18:39.460232: Column escape character: "
[0mFinding file(s).
Found 0 file(s).
```

**Comment by gvenzl** [comment]
On Windows, it seems that the regular ANSI color codes don't work. [Colorama](https://github.com/tartley/colorama) offers a cross-platform library for that. Another option would be not to print color on Windows altogether.

**Comment by jgebal** [comment]
I tend to use ANSICon on windows for colors in console.
https://github.com/adoxa/ansicon
https://liferay.dev/blogs/-/blogs/enable-ansi-colors-in-windows-command-prompt

**Comment by jgebal** [comment]
But definitely, it would be good to detect if console is capable of reporting in color.

**Comment by gvenzl** [comment]
I haven't found a way inside Python to reliably detect whether color coding is available or not. Relying on the user to install something separate is IMO overkill and doesn't solve the problem of "what if the user didn't install it".
Seems like it's enough trouble for the `CMD` on Windows to get any color-coding working without additional steps, so perhaps users don't expect that on Windows.

**Comment by gvenzl** [comment]
Color coding is deactivated on Windows
