### ISSUE TITLE
Error "'ascii' codec can't encode character '\xe9' in position 5: ordinal not in range(128)" thrown on file with unicode data

### ISSUE THREAD

**Issue by gvenzl** [gvenzl/csv2db#36]
When a file includes unicode (or probably non-ascii) data, `csv2db` throws:

```
Loading file allCountries.1000.txt.gz
Error while loading file: allCountries.1000.txt.gz
'ascii' codec can't encode character '\xe9' in position 5: ordinal not in range(128)
```

**Comment by cofin** [comment]
FYI - I ran into this issue yesterday.  In addition to setting the character encoding on the file open, i also had to set the Oracle connection encoding like so:  
```python
conn = cx_Oracle.connect(user,
                                     password,
                                     db_name,
                                     encoding="UTF-8", encoding="UTF-8")
```

**Comment by gvenzl** [comment]
Thanks @cofin,

Indeed it's an issue with the database connection encoding which defaults to `ASCII` on Oracle while it defaults to `UTF-8` on every other major database (opened an ER for that one to change as well).

**Comment by gvenzl** [comment]
Fixed.
