### ISSUE TITLE
Upsert support

### ISSUE THREAD

**Issue by ttrading** [gvenzl/csv2db#41]
I am planning on using this tool to insert some data from CSV to a PSQL12 database. I was wondering is there is any UPSERT support with the current version? Can we set any actions for CONFLICT situations?

Thanks

**Comment by gvenzl** [comment]
Hi @ttrading,

Thanks a lot for considering `csv2db` for your data load and thanks for the great question!

`csv2db` does not provide any out of the box duplicate handling or conflict resolution. The preferred method is to load the data via `csv2db` into a staging table and then perform the merge into the target table manually, having the user decide on the method (`UPSERT`, stored procedure, etc.) and conflict resolution.

I hope this helps, please let us know if you have further questions or insights!

Thx,
