### ISSUE TITLE
-s input for TAB delimited files

### ISSUE THREAD

**Issue by ttrading** [gvenzl/csv2db#42]
What is the separator value for tab delimited files? Is there a list that we can refer to?

Thanks

**Comment by gvenzl** [comment]
Hi @ttrading,

It can be any one-character string that you pass on via the command-line. For tabs, you are probably best off copy/pasting the whole command from a text editor into the command-line. If you are on a Mac, you can also use a trick to type in a tab by pressing `[Ctrl]` + `[v]` first followed by the `[Tab]` key. Don't forget to put the tab between double quotes (`"`).

You can have a look at the examples in the User's Guide: https://github.com/csv2db/csv2db/wiki/User's-Guide#loading-a-file-with-a-different-column-separator

Let us know if you have any further questions!

Thx,
