### ISSUE TITLE
Error generating statement: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by dakweenduck** [gvenzl/csv2db#50]
Picking up issue when files are "UTF-16LE" encoded:

**:~/csv2db# file -i testimportdb.csv
testimportdb.csv: text/plain; charset=utf-16le**

**~/csv2db# ./csv2db generate --debug -s '     '  -f  testimportdb.csv**

**Error generating statement: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte**

A quick fix is to convert the file, then it executes successfully and generates table.

**:~/csv2db# iconv -f UTF-16LE -t UTF-8 testimportdb.csv -o testimportdbdecode.csv**

**:~/csv2db# python3 --version
Python 3.8.5

:~/csv2db# ./csv2db -h
usage: csv2db [-h] {generate,gen,load,lo} ...

The CSV to database command line loader.
Version: 1.5.1**

**Comment by gvenzl** [comment]
Thanks for reporting that issue, @dakweenduck!

I'll take a look and see whether we can automatically detect the file encoding.

**Comment by marttoygoy4** [comment]
![image](https://user-images.githubusercontent.com/80398595/113960331-003ed480-982d-11eb-9284-6b57da61ec07.png)
Sane here

**Comment by gvenzl** [comment]
A new `--encoding` parameter now provides users with the option to specify the input file encoding. Any kind of automatic encoding detection would require an additional third-party library which seems overkill for now.
