### ISSUE TITLE
How to execute the unit tests?

### ISSUE THREAD

**Issue by andygrunwald** [gvenzl/csv2db#52]
Is there a good way to execute all unit tests?

The only way I found was 

```
cd test/python
export PYTHONPATH=../../src/python
python3 functional_tests.py
```

but this feels wrong and executes only the functional_tests Test suite.

**Comment by gvenzl** [comment]
Hey @andygrunwald, you stumbled on a leftover from my original PyCharm days. Indeed, today there are two files, the above `functional_test.py` and another `loading_tests.py` which performs the database load tests. I executed them all via PyCharm having the test databases running locally in Docker containers. Obviously, that's not gonna work going forward, so I'm working on automating the tests via GitHub Actions, see the [gha-tests branch](https://github.com/csv2db/csv2db/tree/gha-tests).
Unfortunately, this is still work in progress, and I will most likely have to split up the database load tests into separate test files (which I kind of knew from the beginning.

To execute the load tests today, one would have to spin up MySQL, Postgres, Oracle, SQL Server and Db2 somewhere, and then execute the steps described in [create_test_infrastructure.sql](https://github.com/csv2db/csv2db/blob/gha-tests/test/resources/test_env/create_test_infrastructure.sql).
However, I do not expect you to do that, I can run the load tests myself until I have them automated.

**Comment by andygrunwald** [comment]
Thanks a lot @gvenzl!

Anything I can help with?
It is also planned to provide an easy way to run the tests locally?
E.g., an automated setup or a few docs on how to do it?

**Comment by gvenzl** [comment]
GitHub Action CI/CD tests are now in place.
