### ISSUE TITLE
Command `generate`: Fail, when header field is empty

### ISSUE THREAD

**Issue by andygrunwald** [gvenzl/csv2db#56]
**What happened**:

Consider a CSV like

```csv
Ingredient code,SR description,Nutrient code,Nutrient value,Nutrient value source,Derivation code,SR AddMod year,Start date,End date,,,
1001,"Butter, salted",203,0.85,SR Legacy,,1976,1/1/2017 0:00,12/31/2018 0:00,,,
1001,"Butter, salted",204,81.11,SR Legacy,,1976,1/1/2017 0:00,12/31/2018 0:00,,,
```

The last three header fields don't contain a name.

If you run

```sh
$ csv2db generate --file fndds_ingredient_nutrient_value.csv --table fndds_ingredient_nutrient_value --quote-identifiers --dbtype mysql
```

You will get an output like

```sql
CREATE TABLE `fndds_ingredient_nutrient_value`
(
 `INGREDIENT_CODE` VARCHAR(1000),
 `SR_DESCRIPTION` VARCHAR(1000),
 `NUTRIENT_CODE` VARCHAR(1000),
 `NUTRIENT_VALUE` VARCHAR(1000),
 `NUTRIENT_VALUE_SOURCE` VARCHAR(1000),
 `DERIVATION_CODE` VARCHAR(1000),
 `SR_ADDMOD_YEAR` VARCHAR(1000),
 `START_DATE` VARCHAR(1000),
 `END_DATE` VARCHAR(1000),
 `` VARCHAR(1000)
);
```

**What you expected to happen**:

I would expect `csv2db` to fail with exit code > 0.
Why?
Because
- I would consider database fields without a name as not a valid database field (how to query it?)
- It might drop data because the last three fields are summed up into one field
- I am not even sure if the `load` command would work

**Anything else we need to know?**:

The `--quote-identifiers` can be ignored for this bug.
This is WIP in https://github.com/csv2db/csv2db/pull/51.

@gvenzl Please let me know what you think about it. If you agree with it, I would apply a PR.

**Comment by gvenzl** [comment]
Fixed.
